version: '3.8'

services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile.api
    ports:
      - 3040:3000
    platform: linux/amd64
    env_file:
      - ../api/.env

  app:
    build:
      context: ../app
      dockerfile: Dockerfile.app
    ports:
      - 4200:4200
    platform: linux/amd64
    # env_file:
    #   - ../app/src/environment/environment.prod.ts

  # sonarqube:
  #   image: sonarqube:lts-community
  #   depends_on:
  #     - sonar_db
  #   environment:
  #     SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
  #     SONAR_JDBC_USERNAME: sonar
  #     SONAR_JDBC_PASSWORD: sonar
  #   ports:
  #     - "9001:9000"
  #   volumes:
  #     - sonarqube_conf:/opt/sonarqube/conf
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_logs:/opt/sonarqube/logs
  #     - sonarqube_temp:/opt/sonarqube/temp

  # sonar_db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: sonar
  #     POSTGRES_PASSWORD: sonar
  #     POSTGRES_DB: sonar
  #   volumes:
  #     - sonar_db:/var/lib/postgresql
  #     - sonar_db_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    # ports:
    #   - 9100:9100

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana-oss
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=gustavo01


volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
